---
- name: 'Reload service files'
  ansible.builtin.systemd:
    daemon_reload: true
  listen: podman_reload_service_files
  when: "ansible_facts['service_mgr'] == 'systemd'"

- name: 'Restart Podman system service'
  ansible.builtin.service:
    name: "{{ podman_service_name }}"
    state: "{{ ansible_facts['is_chroot'] | ansible.builtin.ternary(omit, 'restarted') }}"
  listen: podman_restart
