---
- name: 'Restart Podman system socket'
  ansible.builtin.systemd_service:
    name: "{{ podman_service_name }}.socket"
    scope: "{{ 'user' if podman_api_socket_user != 'root' else 'system' }}"
    daemon_reload: true
    state: restarted
  become: "{{ true if podman_api_socket_user != 'root' else omit }}"
  become_user: "{{ podman_api_socket_user.name | default(podman_api_socket_user) if podman_api_socket_user != 'root' else omit }}"
  when: "ansible_facts['service_mgr'] == 'systemd' and not ansible_facts['is_chroot']"
  listen: podman_socket_restart

- name: 'Restart Podman system service'
  ansible.builtin.service:
    name: "{{ podman_service_name }}"
    state: "{{ ansible_facts['is_chroot'] | ansible.builtin.ternary(omit, 'restarted') }}"
  listen: podman_restart
